# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2/

version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

formats:
  - pdf
  - epub

redirects: {}
